import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Service-Practice Next App",
  description: "Generated by Al Mumeetu Saikat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-100">
        {/* Header */}
        <header className="bg-white shadow-md sticky top-0 z-50">
          <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">

              {/* Logo (Text) */}
              <div className="text-2xl font-bold text-red-600">
                <Link href="/">MyLogo</Link>
              </div>

              {/* Menu */}
              <ul className="flex space-x-8">
                <li>
                  <Link
                    href="/"
                    className="text-gray-700 font-semibold hover:text-red-600 transition-colors"
                  >
                    Web
                  </Link>
                </li>
                <li>

                  <Link
                    href="/about"
                    className="text-gray-700 font-semibold hover:text-red-600 transition-colors"
                  >
                    Android
                  </Link>
                </li>
                <li>
                  <Link
                    href="/service"
                    className="text-gray-700 font-semibold hover:text-red-600 transition-colors"
                  >
                    IOS
                  </Link>
                </li>
                <li>
                  <Link
                    href="/contact"
                    className="text-gray-700 font-semibold hover:text-red-600 transition-colors"
                  >
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
        </header>

        {/* Main Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
